<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ChineseMedicineRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'energy' => 'required|integer',
            'exhausted' => 'required|integer',
            'breathing' => 'required|integer',
            'voice' => 'required|integer',
            'emotion' => 'required|integer',
            'mental' => 'required|integer',
            'loneliness' => 'required|integer',
            'fear' => 'required|integer',
            'over_weight' => 'required|integer',
            'dry' => 'required|integer',
            'cold' => 'required|integer',
            'fear_cold' => 'required|integer',
            'tolerance_cold' => 'required|integer',
            'have_cold' => 'required|integer',
            'stuffy_nose' => 'required|integer',
            'snore' => 'required|integer',
            'allergy' => 'required|integer',
            'urticaria' => 'required|integer',
            'ecchymosis' => 'required|integer',
            'scratch' => 'required|integer',
            'skin_dry' => 'required|integer',
            'pain' => 'required|integer',
            'greasy' => 'required|integer',
            'face_speckle' => 'required|integer',
            'eczema' => 'required|integer',
            'throat_dry' => 'required|integer',
            'mouse_smell' => 'required|integer',
            'fat_abdomen' => 'required|integer',
            'fear_cold_food' => 'required|integer',
            'shit_ache' => 'required|integer',
            'shit_dry' => 'required|integer',
            'tongue_thick' => 'required|integer',
            'vein_thick' => 'required|integer',

            'qixu_score' => 'required|integer',
            'yangxu_score' => 'required|integer',
            'yinxu_score' => 'required|integer',
            'tanshi_score' => 'required|integer',
            'shire_score' => 'required|integer',
            'xieyu_score' => 'required|integer',
            'tebing_score' => 'required|integer',
            'pinghe_score' => 'required|integer',

            'qixu_level' => 'required|integer',
            'yangxu_level' => 'required|integer',
            'yinxu_level' => 'required|integer',
            'tanshi_level' => 'required|integer',
            'shire_level' => 'required|integer',
            'xieyu_level' => 'required|integer',
            'tebing_level' => 'required|integer',
            'pinghe_level' => 'required|integer',

            'qixu_healthcare' => 'required',
            'yangxu_healthcare' => 'required',
            'yinxu_healthcare' => 'required',
            'tanshi_healthcare' => 'required',
            'shire_healthcare' => 'required',
            'xieyu_healthcare' => 'required',
            'tebing_healthcare' => 'required',
            'pinghe_healthcare' => 'required',

            'form_date' => 'required',
            'doctor_name' => 'required',
        ];
    }

    public function attributes()
    {
        $attributes =  parent::attributes(); // TODO: Change the autogenerated stub
        $custom = [
            'energy' => '第(1)题',
            'exhausted' => '第(2)题',
            'breathing' => '第(3)题',
            'voice' => '第(4)题',
            'emotion' => '第(5)题',
            'mental' => '第(6)题',
            'loneliness' => '第(7)题',
            'fear' => '第(8)题',
            'over_weight' => '第(9)题',
            'dry' => '第(10)题',
            'cold' => '第(11)题',
            'fear_cold' => '第(12)题',
            'tolerance_cold' => '第(13)题',
            'have_cold' => '第(14)题',
            'stuffy_nose' => '第(15)题',
            'snore' => '第(16)题',
            'allergy' => '第(17)题',
            'urticaria' => '第(18)题',
            'ecchymosis' => '第(19)题',
            'scratch' => '第(20)题',
            'skin_dry' => '第(21)题',
            'pain' => '第(22)题',
            'greasy' => '第(23)题',
            'face_speckle' => '第(24)题',
            'eczema' => '第(25)题',
            'throat_dry' => '第(26)题',
            'mouse_smell' => '第(27)题',
            'fat_abdomen' => '第(28)题',
            'fear_cold_food' => '第(29)题',
            'shit_ache' => '第(30)题',
            'shit_dry' => '第(31)题',
            'tongue_thick' => '第(32)题',
            'vein_thick' => '第(33)题',

            'qixu_score' => '气虚质得分',
            'yangxu_score' => '阳虚质得分',
            'yinxu_score' => '阴虚质得分',
            'tanshi_score' => '痰湿质得分',
            'shire_score' => '湿热质得分',
            'xieyu_score' => '血瘀质得分',
            'tebing_score' => '特禀质得分',
            'pinghe_score' => '平和质得分',

            'qixu_level' => '气虚质倾向',
            'yangxu_level' => '阳虚质倾向',
            'yinxu_level' => '阴虚质倾向',
            'tanshi_level' => '痰湿质倾向',
            'shire_level' => '湿热质倾向',
            'xieyu_level' => '血瘀质倾向',
            'tebing_level' => '特禀质倾向',
            'pinghe_level' => '平和质倾向',

            'qixu_healthcare' => '中医药保健',
            'yangxu_healthcare' => '中医药保健',
            'yinxu_healthcare' => '中医药保健',
            'tanshi_healthcare' => '中医药保健',
            'shire_healthcare' => '中医药保健',
            'xieyu_healthcare' => '中医药保健',
            'tebing_healthcare' => '中医药保健',
            'pinghe_healthcare' => '中医药保健',

            'form_date' => '填表日期',
            'doctor_name' => '医生签名',
        ];
        return array_merge($attributes,$custom);
    }

    public function messages()
    {
        $messages =  parent::messages(); // TODO: Change the autogenerated stub
        $custom = [
          'required' => '请选择:attribute',
           'integer' => ':attribute值不合法',
            'form_date.required' => ':attribute必填',
            'doctor_name.required' => ':attribute必填',
        ];
        return array_merge($messages,$custom);
    }
}
